# Generated by Django 6.0.6 on 2026-06-04 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DestinoTuristico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCiudad', models.CharField(max_length=100)),
                ('descripcionCiudad', models.TextField()),
                ('imagenCiudad', models.ImageField(upload_to='destinos/')),
                ('precioTour', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ofertaTour', models.BooleanField(default=False)),
            ],
        ),
    ]
