# Generated by Django 6.0.6 on 2026-06-05 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turismo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinoturistico',
            name='imagenCiudad',
            field=models.CharField(max_length=500),
        ),
    ]
